### ISSUE TITLE
Which initrd.img should I use?

### ISSUE THREAD

**Issue by provokateurin** [masneyb/nexus-5-upstream#2]
I extracted a initrd.img from the latest factory image from December 2016, but I can't get the kernel to boot.
When I do `fastboot boot ...` the phone reboots and reboots again then returns booting into Android using the currently installed kernel.
I suspect I'm using the wrong initrd.img, but I can't check, because I didn't build the UART cable yet.

Where do I get the right initrd.img or how can I build it?

**Comment by provokateurin** [comment]
Ok I found out that I have to generate one myself, but maybe there could be some documentation about that? I'm now using the initrd.img for linux 5.3.0 but using the kernel source from your 5.5rc1 branch. The phone doesn't reboot anymore, but also doesn't boot. I'll investigate further after building the UART cable.

**Comment by masneyb** [comment]
@jld3103 : I updated this repository to include what I use as my initramfs.
